baseURL = 'https://j0rd1smit.github.io'
languageCode = 'en-us'
title = 'J0rd1Smit'
copyright = "Jordi Smit - All rights reserved"
summaryLength = 20

[[menu.main]]
name = "Blog"
weight = 100
identifier = "Blog"
url = "/blog"

[[menu.main]]
name = "TIL"
identifier = "til"
weight = 200
url = "/til"

[[menu.main]]
name = "About Me"
identifier = "about"
weight = 300
url = "/about"

[params]

[params.author]
firstName = 'Jordi'
lastName = 'Smit'
jobTitle = 'Machine Learning Engineer'
thumbnail = "media/images/author.jpg"

[params.index]
picture = "/images/author.jpg"
title = "Jordi Smit"
subtitle = "Machine Learning Engineer"

[params.social]
twitter = "j0rd1smit"
github = "j0rd1smit"
linkedin = "👋jordi-smit-8778b51b4"

[permalinks]
blog = '/blog/:title'
til = '/til/:title'
