name: Publish Site

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  pre_commit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: pre-commit/action@v2.0.3

  build-deploy:
    runs-on: ubuntu-20.04
    needs: pre_commit
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1
        lfs: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
